In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [8]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [9]:
np.dot(B,A)

array([[23, 34],
       [31, 46]])

In [10]:
A.T

array([[1, 3],
       [2, 4]])

In [11]:
A

array([[1, 2],
       [3, 4]])

In [12]:
(A+B).T

array([[ 6, 10],
       [ 8, 12]])

In [17]:
print(A.T)
print(B.T)
print(A.T+B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]
[[ 6 10]
 [ 8 12]]


In [14]:
x = np.array([[1,2]])
y = np.array([[1,2], [3,4]])
z = np.array([[5,6]])
print(x)
print(y)
print(z)

[[1 2]]
[[1 2]
 [3 4]]
[[5 6]]


In [15]:
z.T

array([[5],
       [6]])

In [16]:
z

array([[5, 6]])

In [18]:
np.dot(np.dot(x,y), z.T)

array([[95]])

In [19]:
A

array([[1, 2],
       [3, 4]])

In [20]:
I = np.identity(2)
I

array([[ 1.,  0.],
       [ 0.,  1.]])

In [21]:
np.dot(I,A)

array([[ 1.,  2.],
       [ 3.,  4.]])